providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    swarmMode: true
    exposedByDefault: false
    network: proxy
  file:
    filename: "/dynamic.yml"

experimental:
  http3: true

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: web-secure
          scheme: https
  web-secure:
    address: ":443"
    http:
      tls:
        certResolver: le
    http3:
        advertisedPort: 443

certificatesResolvers:
  le:
    # e.g. acme via cloudflare
    acme:
      email: "%%<LETS_ENCRYPT_EMAIL>%%"
      storage: "/acme.json"
      dnsChallenge:
        provider: cloudflare
        delayBeforeCheck: 0

serversTransport:
  # allow self-signed certificates behind proxy
  insecureSkipVerify: true

api:
  insecure: false
  dashboard: false
