{
 "title": "DNS",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Blocking Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 10, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by(docker_node) (blocky_blocking_enabled)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Avg Response Time",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(blocky_request_duration_ms_sum[$__range])) / sum(increase(blocky_request_duration_ms_count[$__range]))"
    }
   ]
  },
  {
   "title": "Request Time (Upstream)",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 0 },
   "targets": [
    {
     "expr": "sum(increase(blocky_request_duration_ms_bucket{response_type=\"RESOLVED\"}[$__range])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Response Total",
   "type": "stat",
   "gridPos": { "h": 2, "w": 10, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(docker_node) (blocky_response_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Prefetch Count",
   "type": "stat",
   "gridPos": { "h": 2, "w": 10, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(docker_node) (blocky_prefetch_count)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "List Counts",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(group) (sum by(docker_node) (blocky_blacklist_cache))",
     "legendFormat": "Blacklisted"
    },
    {
     "expr": "avg by(group) (sum by(docker_node) (blocky_whitelist_cache))",
     "legendFormat": "Whitelisted"
    }
   ]
  },
  {
   "title": "Cache HIT/MISS",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 6, "x": 4, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(blocky_cache_hit_count)", "legendFormat": "HIT" },
    { "expr": "sum(blocky_cache_miss_count)", "legendFormat": "MISS" }
   ]
  },
  {
   "title": "Response Type",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 7, "x": 10, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": " sort_desc(sum by (response_type) (ceil(increase(blocky_response_total[$__range]))))",
     "legendFormat": "{{response_type}}"
    }
   ]
  },
  {
   "title": "Query By Type",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": " sort_desc(sum by (type) (ceil(increase(blocky_query_total[$__range]))))",
     "legendFormat": "{{type}}"
    }
   ]
  }
 ]
}