version: "3"

networks:
  default:
  metrics:
    external: true

services:
  grafana:
    image: grafana/grafana-oss
    volumes:
      - %%<SWARM_DATA>%%/metrics/grafana_data:/var/lib/grafana
    networks:
      - default
    depends_on:
      - prometheus
    deploy:
      labels:
        traefik.http.services.grafana.loadbalancer.server.port: 3000
        traefik.http.services.grafana.loadbalancer.server.scheme: "https"
        traefik.http.routers.grafana.rule: "Host(`grafana.%%<BASE_PROXY_FQDN>%%`)"
        traefik.http.routers.grafana.tls.domains[0].main: "%%<BASE_PROXY_FQDN>%%"
        traefik.http.routers.grafana.tls.domains[0].sans: "*.%%<BASE_PROXY_FQDN>%%"
        traefik.http.routers.grafana.tls.certresolver: "le"
        traefik.http.routers.grafana.entrypoints: "web-secure"
        traefik.http.routers.grafana.tls: "true"
        traefik.enable: "true"
    user: nobody

  prometheus:
    image: prom/prometheus
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - %%<SWARM_DATA>%%/metrics/prometheus_config.yml:/etc/prometheus/prometheus.yml:ro
      - %%<SWARM_DATA>%%/metrics/prometheus_data:/prometheus
    # ports:
    #   - "9090:9090"
    networks:
      - default
      - metrics
    user: nobody:%%<DOCKER_GID>%%
