version: "3"

networks:
  default:
  proxy:
    external: true

services:
  agent:
    # add -alpine for smaller image size
    image: portainer/agent:2.17.0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - default
    deploy:
      mode: global

  portainer:
    # add -alpine for smaller image size
    image: portainer/portainer-ce:2.17.0
    command: -H tcp://tasks.agent:9001 --tlsskipverify
    ports:
      - "8000:8000"
    volumes:
      - %%<SWARM_DATA>%%/portainer/data:/data
    networks:
      - default
      - proxy
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
      labels:
        traefik.http.services.portainer.loadbalancer.server.port: 9443
        traefik.http.services.portainer.loadbalancer.server.scheme: "https"
        traefik.http.routers.portainer.rule: "Host(`portainer.%%<BASE_PROXY_FQDN>%%`)"
        traefik.http.routers.portainer.tls.domains[0].main: "%%<BASE_PROXY_FQDN>%%"
        traefik.http.routers.portainer.tls.domains[0].sans: "*.%%<BASE_PROXY_FQDN>%%"
        traefik.http.routers.portainer.tls.certresolver: "le"
        traefik.http.routers.portainer.entrypoints: "web-secure"
        traefik.http.routers.portainer.tls: "true"
        traefik.enable: "true"
