scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: dns
    dockerswarm_sd_configs:
      - host: unix:///var/run/docker.sock
        role: tasks
    relabel_configs:
      - source_labels: [__meta_dockerswarm_task_desired_state]
        regex: running
        action: keep
      - source_labels: [__meta_dockerswarm_container_label_prometheus_export]
        regex: dns_blocky
        action: keep
      - source_labels: [__address__]
        regex: "([^:]+):\\d+"
        target_label: __address__
        replacement: $1:4000
      - source_labels: [__meta_dockerswarm_node_hostname]
        target_label: docker_node
